server:
  port: 8082

spring:
  application:
    name: receiver-service

logging:
  file:
    name: logs/receiver-service.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
