server:
  port: 8081

spring:
  application:
    name: caller-service

receiver:
  base-url: http://localhost:8082

logging:
  file:
    name: logs/caller-service.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
